# Generated by Django 4.2.5 on 2023-09-20 13:50

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_lesson_productaccess_lessonview_lessonproduct'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='LessonView',
            new_name='LessonScan',
        ),
    ]
