# Generated by Django 4.2.5 on 2023-09-21 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_lessonview_lessonscan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lessonscan',
            old_name='viewed',
            new_name='view_status',
        ),
        migrations.RenameField(
            model_name='lessonscan',
            old_name='viewed_time',
            new_name='view_time',
        ),
        migrations.AddField(
            model_name='lesson',
            name='products',
            field=models.ManyToManyField(to='app.product'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='duration',
            field=models.PositiveIntegerField(),
        ),
    ]
